### ISSUE TITLE
Transition to OpenSSL

### ISSUE THREAD

**Issue by kravietz** [jeroennijhof/pam_tacplus#39]
Looking at the library code I think the time has come to finally get rid of this 90's code and transition to proper RAND_pseudo_bytes() from OpenSSL. We would also use their MD5 implementation instead of the bundled one. This would eventually end bugs related to archaic handling of /dev/urandom and properly handle all other situations related to entropy gathering. The code was originally written back in 90's when there was no /dev/urandom and this is why this is handled in such awkward way.

The code changes would be few (I did that already in the tacc project) and the main change would be in that the package would now depend on OpenSSL.

I just wanted to get opinnions and comments before actually implementing that.

**Comment by kravietz** [comment]
Completed in latest version.

**Comment by daveolson53** [comment]
Paweł Krawczyk <notifications@github.com> wrote:

> Completed in latest version.

When building this in debian, I get the warning about linking GPL code
with openssl, which has historically been a real problem for people,
because the two licenses aren't compatible.

(It's not a debian-specific issue, it's just that lintian notes and
warns about it.)

Was that issue considered, and if so, how was it resolved?

Or was it just ignored?

Also, pam_tacplus.c seems to still unconditionally call magic(), rather
than having the ifdefs that are in libtac/lib, so I don't quite see how
this could run successfully when using openssl, since magic() is UND ?
Am I missing something, or did a change not get committed?

Thanks,

Dave Olson
olson@cumulusnetworks.com
